### ISSUE TITLE
Please accept my genuine and heartfelt gratitude

### ISSUE THREAD

**Issue by Ataraksea** [vinjn/one-minute-omniverse#2]
I'm not exaggerating when I say that you've just saved me double digit hours worth of work by putting this all together and making it publicly available.   Work that undoubtedly would have involved a great deal of banging my head against a wall while slowly losing my grip on whatever sanity I've somehow managed to hold onto this long.  I digress though, my point is, thank you so very much for doing so!

**Comment by vinjn** [comment]
Glad it's helpful
